# Generated by Django 5.0.3 on 2024-10-20 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ انتهاء الإيجار'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='properties.property', verbose_name='العقار'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ بدء الإيجار'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='properties.tenant', verbose_name='المستأجر'),
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'ضعيف'), (2, 'متوسط'), (3, 'جيد'), (4, 'ممتاز')], verbose_name='التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property', verbose_name='العقار')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.tenant', verbose_name='المراجع')),
            ],
        ),
    ]
